# Generated by Django 5.2.7 on 2025-10-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('marque_modele', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('categorie', models.CharField(choices=[('Drones', 'Drones'), ('Robots', 'Robots'), ('Informatique', 'Informatique'), ('Électronique', 'Électronique'), ('Maintenance', 'Maintenance'), ('Divertissement', 'Divertissement'), ('Actionneurs', 'Actionneurs'), ('Accessoires', 'Accessoires'), ('Composants', 'Composants'), ('Stockage', 'Stockage')], max_length=50)),
                ('quantite', models.PositiveIntegerField()),
                ('etat', models.CharField(max_length=100)),
                ('emplacement', models.CharField(blank=True, max_length=200)),
                ('utilisabilite', models.CharField(blank=True, max_length=100)),
                ('responsable', models.CharField(blank=True, max_length=100)),
                ('remarque', models.TextField(blank=True)),
                ('suggestion', models.TextField(blank=True)),
            ],
        ),
    ]
