# Generated by Django 5.2.7 on 2025-10-06 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horuslabs_inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='categorie',
        ),
    ]
