# Generated by Django 5.2.7 on 2025-10-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horuslabs_inventory', '0002_remove_equipement_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='categorie',
            field=models.CharField(choices=[('Drones', 'Drones'), ('Robots', 'Robots'), ('Informatique', 'Informatique'), ('Électronique', 'Électronique'), ('Maintenance', 'Maintenance'), ('Divertissement', 'Divertissement'), ('Actionneurs', 'Actionneurs'), ('Accessoires', 'Accessoires'), ('Composants', 'Composants'), ('Stockage', 'Stockage'), ('Écrans et affichage', 'Écrans et affichage'), ('Modules de communication', 'Modules de communication'), ('Capteurs', 'Capteurs'), ('Cartes mémoire et stockage', 'Cartes mémoire et stockage')], default='Drones', max_length=50),
        ),
    ]
